# -*- coding: utf-8 -*-
"""Scrapping Data from Real Websites.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Fp4ddbdATrlyA13CvG1tk5a27EJSOYK
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

url='https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'
page=requests.get(url)

soup=BeautifulSoup(page.text,'html.parser')
print(soup)

table=soup.find_all('table',class_='wikitable sortable')[0]

headers = []
for th in table.find('tr').find_all('th'):
    headers.append(th.text.strip())

rows = []
for tr in table.find_all('tr')[1:]:
    cells = tr.find_all('td')
    if len(cells) > 0:
        row = [cell.text.strip() for cell in cells]
        rows.append(row)

df = pd.DataFrame(rows, columns=headers)

df

#file_path = r'C:\Users\anjal\OneDrive\web_scraping.csv'
df.to_csv('webscraping.csv',index=0)

